### ISSUE TITLE
tests are failing (selinux?)

### ISSUE THREAD

**Issue by ignatenkobrain** [Stebalien/xattr#9]
```
test test_multi ... FAILED
test test_fd ... FAILED
test test_path ... FAILED

failures:

---- test_multi stdout ----
	thread 'test_multi' panicked at 'assertion failed: items.remove(&*it)', tests/main.rs:59

---- test_fd stdout ----
	thread 'test_fd' panicked at 'assertion failed: `(left == right)` (left: `Some("security.selinux")`, right: `None`)', tests/main.rs:16
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- test_path stdout ----
	thread 'test_path' panicked at 'assertion failed: `(left == right)` (left: `Some("security.selinux")`, right: `None`)', tests/main.rs:33
```

**Comment by Stebalien** [comment]
Does that fix it? Also, do you need me to cut a release (I usually don't for test case changes).

**Comment by ignatenkobrain** [comment]
@Stebalien better, but one test still fails:
```
running 3 tests
test test_multi ... ok
test test_fd ... ok
test test_path ... FAILED

failures:

---- test_path stdout ----
	thread 'test_path' panicked at 'assertion failed: `(left == right)` (left: `1`, right: `0`)', tests/main.rs:44
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    test_path

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured
```

**Comment by Stebalien** [comment]
Gah. Sorry, that should be fixed now.

**Comment by ignatenkobrain** [comment]
@Stebalien thanks for fixing... About release -- up to you. I can just apply two patches in Fedora.

**Comment by Stebalien** [comment]
I've cut a 0.1.11 release. Easier to do that than maintain patches
downstream.

**Comment by ignatenkobrain** [comment]
Thanks a lot!
